{
 "title": "Количество запросов",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request to /api",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{instance=\"demo-rest:8080\", uri=\"/api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request to /api/books",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{instance=\"demo-rest:8080\", uri=\"/api/books\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request to /api/authors",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{instance=\"demo-rest:8080\", uri=\"/api/authors\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}